name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka"
          SHOW_OS: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_UPDATED_DATE: "True"
          COMMIT_MESSAGE: "Updated the Stats"
          LOCALE: "en"
